"""
Simulates Electronic Warfare interference against a source type in two
distinct ways:

- Degradation (toggle/is_degraded/degrade_reading): jamming-style —
  readings are dropped or emitted with reduced confidence. Modeled first,
  documented above.

- Spoofing (toggle_spoof/is_spoofing/maybe_spoof_reading): an adversary
  injecting a fabricated-but-plausible contact into a source's feed. This
  is deliberately indistinguishable from a genuine reading — the spoofed
  reading is generated by the exact same generator function a real feed
  uses, not tagged or filtered in any way, because that's what makes
  spoofing a real vulnerability worth simulating rather than a trivially
  detectable anomaly. A spoofed reading can flow all the way through
  fusion and reach TARGET/ENGAGE like any real one — left that way on
  purpose, not an oversight.
"""

import random

from backend.app.models.schemas import SensorReading, SourceType

# The four sensor feeds EW applies to. HUMINT is excluded: degradation and
# spoofing here model RF interference against a sensor (dropped readings,
# confidence penalties, injected phantom contacts), and a written human
# report filed via /ingest/humint isn't subject to that. Excluded from the
# two status dicts rather than from the toggle methods, so the dashboard
# only offers jam/spoof controls for sources they can actually affect.
EW_APPLICABLE_SOURCES = [s for s in SourceType if s is not SourceType.HUMINT]


class EWSimulator:
    def __init__(self):
        self._degraded_sources: set[SourceType] = set()
        self._spoofing_sources: set[SourceType] = set()

    def toggle(self, source_type: SourceType) -> bool:
        """Flip degradation on/off for a source. Returns new state."""
        if source_type in self._degraded_sources:
            self._degraded_sources.remove(source_type)
            return False
        self._degraded_sources.add(source_type)
        return True

    def is_degraded(self, source_type: SourceType) -> bool:
        return source_type in self._degraded_sources

    def status(self) -> dict:
        return {s.value: (s in self._degraded_sources) for s in EW_APPLICABLE_SOURCES}

    def degrade_reading(self, reading: SensorReading) -> SensorReading | None:
        """Either drop the reading (simulating jamming blackout) or return
        it with a confidence penalty and a `degraded` flag set."""
        if random.random() < 0.4:
            return None  # signal lost entirely this cycle

        reading.confidence = round(reading.confidence * random.uniform(0.3, 0.6), 2)
        reading.degraded = True
        return reading

    def toggle_spoof(self, source_type: SourceType) -> bool:
        """Flip spoofing on/off for a source. Returns new state."""
        if source_type in self._spoofing_sources:
            self._spoofing_sources.remove(source_type)
            return False
        self._spoofing_sources.add(source_type)
        return True

    def is_spoofing(self, source_type: SourceType) -> bool:
        return source_type in self._spoofing_sources

    def spoof_status(self) -> dict:
        return {s.value: (s in self._spoofing_sources) for s in EW_APPLICABLE_SOURCES}

    def maybe_spoof_reading(self, source_type: SourceType, generator) -> SensorReading | None:
        """If spoofing is active for this source, there's a chance a
        fabricated reading is generated this cycle using `generator` —
        the same function the feed uses for genuine readings — so the
        result is structurally identical to a real one. Returns None if
        spoofing is inactive, or on the (majority of) cycles where no
        phantom contact appears."""
        if source_type not in self._spoofing_sources:
            return None
        if random.random() < 0.3:
            return generator()
        return None


# Module-level singleton — simple for a single-process scaffold.
# Swap for a Redis-backed shared state if you move to multi-worker (see
# docker-compose.yml's redis service).
ew_simulator = EWSimulator()
